#!/bin/bash

echo "####### (Re)Installing killswitch #######"
echo "####### Note v6  is expected to fail #######"
iptables-restore < /app/killswitch/ipv4
ip6tables-restore < /app/killswitch/ipv6

sleep 60
