version: '3'
services:
  vpn:
    image: rooteth/nordvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 103.86.96.100
      - 103.86.99.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ovpn-data:/app/ovpn/config
    environment:
      - USERNAME=<nordvpn_username>
      - PASSWORD=<nordvpn_password>
      - LOCAL_NETWORK=192.168.1.0/24
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
      - net.ipv6.conf.eth0.disable_ipv6=1
    networks:
      - default
    ports:
      - 8118:8118
    restart: always

volumes:
  ovpn-data: